
services:
  # 1. Serviço do Servidor Express
  app:
    container_name: Epm_Server
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db        # HOST: O nome do serviço 'db' (Correto!)
      DB_USER: Khemer
      DB_PASSWORD: Khemer0#
      DB_NAME: epm_db
      DB_PORT: 3306
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      
    # CORREÇÃO 2: Espera o MySQL ficar HEALTHY
    depends_on:
      db:
        condition: service_healthy
        

  # 2. Serviço do Banco de Dados MySQL
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Khemer_admin 
      MYSQL_DATABASE: epm_db
      MYSQL_USER: Khemer
      MYSQL_PASSWORD: Khemer0#
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck: # <-- SEÇÃO CORRIGIDA PARA MYSQL
      # CORREÇÃO 1: Comando MySQL para checar o status
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10 # Aumentado para garantir a inicialização completa
      start_period: 20s # Dê um período inicial para o MySQL começar a responder

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "80:80"
    environment:  
      PMA_HOST: db
      PMA_USER: Khemer
      PMA_PASSWORD: Khemer0#  
      PMA_PORT: 3306
    depends_on:
      db:
        condition: service_healthy    
      


# Volumes definidos
volumes:
  mysql_data:
    driver: local