services:
  # 1. Serviço do Servidor Express
  app:
    container_name: Epm_Server
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: Khemer
      DB_PASSWORD: Khemer0#
      DB_NAME: epm_db
      DB_PORT: 3306
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jitsi-network

  # 2. Serviço do Banco de Dados MySQL
  db:
    container_name: mysql_db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Khemer_admin
      MYSQL_DATABASE: epm_db
      MYSQL_USER: Khemer
      MYSQL_PASSWORD: Khemer0#
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - jitsi-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: Khemer
      PMA_PASSWORD: Khemer0#
      PMA_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - jitsi-network

  # --- SEÇÃO JITSI ATUALIZADA ---
  wb:
    container_name: Jitsi
    image: jitsi/web:stable-9584
    restart: always
    ports:
      - '9000:80' 
      - '9443:443'
    volumes:
      - ~/.jitsi-meet-cfg/web:/config:Z
      # MAPEAMENTO DOS NOVOS CERTIFICADOS:
      - ./192.168.110.127+2.pem:/config/certs/cert.crt:Z
      - ./192.168.110.127+2-key.pem:/config/certs/cert.key:Z
    environment:
      PUBLIC_URL: http://localhost:9000
    networks:
      - jitsi-network

  prosody:
    image: jitsi/prosody:stable-9584
    restart: always
    expose:
      - '5222'
      - '5347'
      - '5280'
    volumes:
      - ~/.jitsi-meet-cfg/prosody/config:/config:Z
    networks:
      - jitsi-network
    environment:
      - JICOFO_AUTH_PASSWORD=Khemer0#
      - JVB_AUTH_PASSWORD=Khemer0#

  jicofo:
    image: jitsi/jicofo:stable-9584
    restart: always
    volumes:
      - ~/.jitsi-meet-cfg/jicofo:/config:Z
    networks:
      - jitsi-network
    environment:
      - XMPP_SERVER=prosody
      - JICOFO_AUTH_PASSWORD=Khemer0#

  jvb:
    image: jitsi/jvb:stable-9584
    restart: always
    ports:
      - '10000:10000/udp'
    expose:
      - '9090'
    volumes:
      - ~/.jitsi-meet-cfg/jvb:/config:Z
    networks:
      - jitsi-network
    environment:
      - XMPP_SERVER=prosody
      - JVB_AUTH_PASSWORD=Khemer0#

# --- DECLARAÇÃO GLOBAL DE REDES E VOLUMES ---
networks:
  jitsi-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local